### ISSUE TITLE
Memory leaking...

### ISSUE THREAD

**Issue by interhive** [APItools/monitor#39]
I seem to have developed a pretty severe memory leak in the nginx worker process after months of very smooth operation. I have not made any changes to the APItools configuration or pipelines in months.

I've rebooted and still seem to be plagued by 80-100% CPU usage and what appears to be a memory leak. It's growing at about 1MB of usage every two seconds.

![screen shot 2015-03-07 at 12 00 05 pm](https://cloud.githubusercontent.com/assets/8636/6542576/d49981da-c4c1-11e4-9c6b-035c5ca574ed.png)

I'm not really sure how to diagnose the issue and, hopefully, this is something you openresty/nginx gurus can help with. I'm running the latest APItools via Debian package install. There are very few requests to this instance, which is what is boggling my mind. Also, it's weird that it just cropped up out of nowhere.

In any case, please let me know what's needed for debugging, as there aren't many articles out there for tracking down memory leaks in nginx -- especially ones that seemingly came out of nowhere and for no reason whatsoever. 

Thanks!

**Comment by kikito** [comment]
Hi @interhive ,

We're investigating this issue, but it is difficult for us to replicate - we have been testing nginx for a while now and never saw a 80% CPU usage. This looks like more than a simple leak - it looks like nginx is trapped in some kind of nasty loop, probably consuming more memory than it has time to release.

First of all, can you confirm that nothing special happened on the server prior to this problem? Even if it seems unrelated - installing another package, or a simple `apt-get upgrade` of some other tool. Sometimes this has ramifications.

> I've rebooted and still seem to be plagued by 80-100% CPU usage

When you say "reboot", you mean "reboot the server", or just nginx? If it's just nginx, make sure you are "restarting the service", instead of just "reloading" (rebooting the server should to it). It has been reported that nginx sometimes does not release memory when reloading.

Rebooting the Nginx server completely (instead of reloading) should also clear up Nginx's shared dictionaries. It is possible that they contain corrupted data and that is creating 

If that does not do it, then it's possible are that some of the data in the redis db is corrupted and it's provoking some sort of short-circuit in the monitor. If you are ok losing the last traces of the db, I would try emptying the redis db completely and re-configuring the monitor with the services you use. You can do so in the redis-cli:

```
$ redis-cli
> EVAL  "for _,k in ipairs(redis.call('keys', 'jor/*')) do redis.call('del', k) end" 0
```

This will delete the redis db completely. It should destroy any possibility of a loop ocurring in your machine. You will however need to reconfigure it after the fact - [starting on this step](https://docs.apitools.com/docs/on-premise/#testing-&-port-configuration). Then re-add your apitools service.

If the high CPU usage continues after a reboot and a redis cleanup, then it is possible that there is something wrong with the server itself. I would suggest trying to install it on a different server.

**Comment by interhive** [comment]
No upgrades, no changes in configuration -- which is what made it weird to happen out of the blue.

I rebooted the machine, not just the nginx instance.

I wound up cloning a 14 day old backup onto a new instance and switching over the DNS to point at that. I've shut down the misbehaving instance but I will spool it up and try fiddling with redis, as you recommended.

This brings a feature request to light: import/export of services and pipelines. So, when a redis instance does have to be blown away, there's an easy route to putting the thing back together again rather than manually recreating the pipelines.

Thanks for the help!

**Comment by kikito** [comment]
Ok, @interhive . I have created a new issue for the import/export of services and pipelines.

I will close down this issue for now, ase we've found nothing obvious which could provoke the high cpu consumption. Please do reopen if the problem manifests itself again.
