### ISSUE TITLE
Add keys middleware code is the test not the middleware code

### ISSUE THREAD

**Issue by picsoung** [APItools/monitor#45]
When you add from the list of suggested middleware the `Add Keys` middleware, it gives you the code of the test instead of the code of the actual middleware.

![apitools_traffic_monitor](https://cloud.githubusercontent.com/assets/172072/7630667/a75ae266-fa38-11e4-9ada-3edce1428a6b.png)

**Comment by picsoung** [comment]
also reported by another user :)

ping @kikito

**Comment by kikito** [comment]
Hi @picsoung,

This is fixed now. I have tested it in production.

The problem was a typo in the `apitools.json` file defining the add keys middleware - instead of having a "spec" entry, it was named "files". So the code of the spec was treated like the code of the middleware.

Here's the change which fixed the issue (after telling brain to reload the middlewares from github)

https://github.com/APItools/middleware/commit/159ec383a9255192aea4ace822e8e9bc3c5948cc
